### ISSUE TITLE
[a small bug] lspconfig 启动重复

### ISSUE THREAD

**Issue by Liksium** [iChunyu/nvim#1]
https://github.com/iChunyu/nvim/blob/27a1723b0253abe114dde6aa6c750a4adeee5051/lua/plugins/lsp.lua#L34-L42 这里好像重复设置了 `matlab_ls`，根据 nvim-lspconfig 文档 [neovim/nvim-lspconfig: Quickstart configs for Nvim LSP](https://github.com/neovim/nvim-lspconfig/tree/master?tab=readme-ov-file#troubleshooting) ：

> 5. Do not call setup {} twice for the same server. The second call to setup {} will overwrite the first.

这样会覆盖设置。

**Comment by iChunyu** [comment]
嗨，感谢提醒，已经把 `matlab_ls` 从 34 行的列表中删除了，在 40 行后面单独进行配置。
（好久没用 nvim 写 MATLAB 的说）
